source 'https://rubygems.org'

ruby '2.4.1'
gem 'em-http-request', '~> 1.1', '>= 1.1.5'
gem 'oj'
gem 'fastimage', '~> 2.1'
gem 'em-synchrony', '~> 1.0', '>= 1.0.6'
gem 'telegram-rb', github: 'longnh92/telegram-rb', require: 'telegram'
gem 'eventmachine'
gem 'byebug'
